version: '3.9'

services:
  python:
    container_name: 'python'
    build:
      context: ./package
    volumes:
      - .:/data/app
    tty: true

  mongodb:
    image: mongo
    container_name: 'mongo'
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db
    environment:
      - MONGO_INITDB_DABATASE=dna
      - MONGO_INITDB_ROOT_USERNAME=comet
      - MONGO_INITDB_ROOT_PASSWORD=12345


