# Dockerfile, Image, Container

FROM python:3.8-slim-buster

WORKDIR /data/app

RUN pip install requests numpy pandas tqdm scikit-learn tensorflow pymongo dnspython

#docker container run -it -v ${pwd}:/app test bash
